FROM alpine:3.20

RUN apk add --no-cache bash netcat-openbsd wget clickhouse-client kcat

COPY startup_script.sh /usr/local/bin/startup_script.sh
RUN chmod +x /usr/local/bin/startup_script.sh

ENTRYPOINT ["/usr/local/bin/startup_script.sh"]
