apiVersion: 1

datasources:
  - name: ClickHouse
    type: clickhouse
    access: proxy
    url: http://clickhouse:8123
    user: ${CLICKHOUSE_GRAFANA_USER}
    password: ${CLICKHOUSE_GRAFANA_PASSWORD}
    jsonData:
      tlsSkipVerify: true
      defaultDatabase: 'events'
    editable: true
